# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bbd989ce0dc4206d432b77f2408cae8187e6b98ddbd76de1483a1de54664699b4f2c6c41bb98d47f865ffeed449f2f4c5d93388d46b31e48ec8a88b65667308

test:
  secret_key_base: 403a45158a42eff4755ea5ef1cabcf34a21fc0e0c1627af217857d3e5199b5ade70818322828f6599097c1805f01cc70c3db8d4af2a86fcee2c373ab60b64f5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
